# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IoTConnect2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IoTConnect2
	 pod 'CocoaMQTT', :git => "https://github.com/emqx/CocoaMQTT.git", :tag => "2.1.8"


end
